create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  organization text,
  service text not null,
  message text not null
);

alter table public.contact_inquiries enable row level security;

create policy "Allow public contact form submissions"
on public.contact_inquiries
for insert
to anon
with check (true);
